Правки теста

diff --git a/.github/workflows/ui-tests.yml b/.github/workflows/ui-tests.yml
--- a/.github/workflows/ui-tests.yml
+++ b/.github/workflows/ui-tests.yml
@@ -10,19 +10,19 @@ on:
 jobs:
   ui-tests:
     runs-on: ubuntu-latest
-#    services:
-#      selenoid:
-#        image: aerokube/selenoid:latest-release
-#        ports:
-#          - 4444:4444
-#        volumes:
-#          - ./config:/etc/selenoid
-#        options: >-
-#          --privileged
-#          --health-cmd "wget --no-verbose --tries=1 --spider http://localhost:4444/status || exit 1"
-#          --health-interval 10s
-#          --health-timeout 5s
-#          --health-retries 5
+    #    services:
+    #      selenoid:
+    #        image: aerokube/selenoid:latest-release
+    #        ports:
+    #          - 4444:4444
+    #        volumes:
+    #          - ./config:/etc/selenoid
+    #        options: >-
+    #          --privileged
+    #          --health-cmd "wget --no-verbose --tries=1 --spider http://localhost:4444/status || exit 1"
+    #          --health-interval 10s
+    #          --health-timeout 5s
+    #          --health-retries 5
 
     steps:
       - name: Checkout repository
@@ -36,10 +36,10 @@ jobs:
 
       - name: Install Docker Compose
         run: |
-          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64" -o 
-          /usr/local/bin/docker-compose
-          sudo chmod +x /usr/local/bin/docker-compose
-
+          DOWNLOAD_URL="https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64"
+          TARGET_PATH="/usr/local/bin/docker-compose"
+          sudo curl -L "$DOWNLOAD_URL" -o "$TARGET_PATH"
+          sudo chmod +x "$TARGET_PATH"
       - name: Start Selenoid
         run: docker-compose up -d
 
