Запуск 27/ Matrix browser

diff --git a/.github/workflows/ui-tests.yml b/.github/workflows/ui-tests.yml
--- a/.github/workflows/ui-tests.yml
+++ b/.github/workflows/ui-tests.yml
@@ -82,17 +82,29 @@ jobs:
           sudo mv allure-2.34.0 /opt/allure
           sudo ln -s /opt/allure/bin/allure /usr/bin/allure
 
+#      - name: Generate Allure Report
+#        run: |
+#          mkdir -p allure-report
+#          allure generate target/allure-results --clean -o allure-report || echo "::warning::Allure generation failed"
+#          echo "Last generated: $(date)" > allure-report/build-info.txt
+
+#      - name: Upload Allure Report as artifact
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: test-results-${{ matrix.browser }}-${{ github.run_id }}
+#          path: allure-report
+
       - name: Generate Allure Report
         run: |
-          mkdir -p allure-report
-          allure generate target/allure-results --clean -o allure-report || echo "::warning::Allure generation failed"
-          echo "Last generated: $(date)" > allure-report/build-info.txt
+          mkdir -p allure-report-${{ matrix.browser }}
+          allure generate target/allure-results --clean -o allure-report-${{ matrix.browser }}
+          echo "Browser: ${{ matrix.browser }}" > allure-report-${{ matrix.browser }}/browser-info.txt
 
-      - name: Upload Allure Report as artifact
+      - name: Upload Artifact
         uses: actions/upload-artifact@v4
         with:
-          name: test-results-${{ matrix.browser }}-${{ github.run_id }}
-          path: allure-report
+          name: allure-report-${{ matrix.browser }}
+          path: allure-report-${{ matrix.browser }}
 
       - name: Deploy Allure Report to GitHub Pages
         if: success()
